### ISSUE TITLE
Feature Request: Calendar API support

### ISSUE THREAD

**Issue by PitchBright** [ProjectZulu/Project-Zulu#104]
This API is in the works : https://github.com/CallMeFoxie/Calendar

Requesting JAS support Calendar API with tags of some sort, to allow for control of mob spawning per season.

Usage examples:
Ducks != Winter
Bears != Winter
Bees = Summer
Groundhogs = Spring ;-)

**Comment by Crudedragos** [comment]
Wrong tracker, this is /was for project Zulu.

No worries, I've already recreated the issue on the Jas issue tracker : JAS 153

**Comment by PitchBright** [comment]
Crap… sorry about that. My bad. _blush_
