### ISSUE TITLE
liteloader breaks sounds from Project-Zulu mobs

### ISSUE THREAD

**Issue by snake2332** [ProjectZulu/Project-Zulu#31]
Hello there. I am using a modified version of FTB Ultimate, so Minecraft 1.4.7. I love your mob. However, I don't get sound from the mobs at all. I do from other mods' mobs, like Atmosmobs. I narrowed it down to liteloader causing the problem. I remove liteloader, rebuild jar, then I get sound from all Zulu mobs. I put liteloader back in, rebuild jar, and sure enough the sound is broken. I don't really want to remove liteloader because I need it for the voxel mods.

Any idea why this happens? I see liteloader replaces bch.class & \classes\g.bin

**Comment by Crudedragos** [comment]
Installed liteloader from http://www.minecraftforum.net/topic/467504-151-macro-keybind-mod-0982-and-liteloader-for-151/
Using as 'Jar' mods: Forge 6.6.2.534 (1.4.7), liteloader_1.4.7
Using as 'mod' mods: ProjectZuluCompletev0.6.5b

Sound seems to work fine. If you could be more specific on which sounds are not playing, I could investigate further. A log for a world setup with the problem would be appreciated.

You could also try reloading the sound egine when in game, press F3+S.

Don't know what g.bin is but bch is RenderLightningBolt.

**Comment by snake2332** [comment]
Thanks for addressing this. I will test a couple things myself and try to get some more deets to you.

Oh, the sounds that aren't playing are: all of the OGG's in the \core\sounds\ folder, so like ostrich & mummy noises when you hit them.

**Comment by snake2332** [comment]
I am building a new test setup and so far it is working, like you said. Hopefully I will find the rogue 3rd mod that is breaking it, hehe. Kinda hard when you have 110 mods to narrow down.

**Comment by Crudedragos** [comment]
Putting this here so everything is together. http://www.minecraftforum.net/topic/1468127-151forgebuffarmor-bar-mods-project-zulu-better-overworld-v1031-extrabiomesxl-support-update-haunted-texture-fix/page__st__920#entry21801980

> I figured out that the LiteLoader voxel mod known as "integrated.soundpack.litemod" causes all the sound FX to break in ProjectZulu. Just thought I'd point that out for anyone else that is using FTB modpacks and have no sound from the mobs.

**Comment by Crudedragos** [comment]
Installed Field the Beast Ultimate alongside PZv0.6.5b
Confirmed Issue via:
Run --> No Sound --> Remove integrated.soundpack.litemod --> Run --> Sound
Solution via:
Run --> No Sound --> F3 + S --> Sound Works Fine
Considering the 'fix' is trivial and other OS mods add sounds in an identical fashion, such as EE3. Closing issue for now.
