### ISSUE TITLE
Spawner GUI Doesn't use all "Value" field space

### ISSUE THREAD

**Issue by Blue001** [ProjectZulu/Project-Zulu#43]
The "value" field in the GUI isn't set to show more than 3 digits when there is room for at least 5-6.

![image](https://f.cloud.github.com/assets/4544521/574096/6cb7c84c-c7c0-11e2-82af-d0cb0971a900.png)

A mock up of what I assume it should look like.
![image](https://f.cloud.github.com/assets/4544521/574111/b05e89f0-c7c0-11e2-8112-ad596349567e.png)

**Comment by Crudedragos** [comment]
There is clearly more room for increased precision. Not sure why I limited to 3.

**Comment by Crudedragos** [comment]
Closed via 5707fef
