### ISSUE TITLE
Feature Request : "Force Spawn" toggle for Custom mob spawners.

### ISSUE THREAD

**Issue by Blue001** [ProjectZulu/Project-Zulu#44]
As you have created JAS and It has a way to spawn a mob anywhere, overriding its original spawn code (light requirements) , I assume this is possible. 
A toggle on the custom mob spawner to allow for it to force spawn any mob regardless of  its normal requirements would be great to see.

Things that prevent a spawner from spawning a mob from a custom spawner.
Light and Torchlight
Requires X Block at feet (animals)

A single "force spawn" toggle would do it I think.

**Comment by Crudedragos** [comment]
Saw the forum post and was going to reply that I'd just steal the tag system from JAS.

Irrelevant to me creating JAS, it is open source under Apache for this exact code-reuse utility. So +1 for open source.

Until I create a gui in JAS, this would likely just be a long text string to write the tags.

**Comment by Crudedragos** [comment]
Closed via a833aea
