### ISSUE TITLE
Bug : Limited Mob Spawner doesn't like "Special Mobs" mod.

### ISSUE THREAD

**Issue by Blue001** [ProjectZulu/Project-Zulu#45]
Got a crash when trying to set a custom limited mob spawner to spawn a "Special Skeleton" from the mod "Special Mobs"

It crashed as soon as I selected the mob name from the list.
Here is the crash info.

Admin Edit: Stacktrace on pastebin
http://paste.minecraftforge.net/view/2bbc28c1#

**Comment by Crudedragos** [comment]
This seems to be working fine for me. PZv1.0.3.7Complete with SpecialMobs 2.4.2

**Comment by Blue001** [comment]
All other "Special Mobs" mobs seem to work fine, except the "Random" version mob specifically called "Special Skeleton"
This is how I replicate it....first select another mob... lets say "Bat", to have the GUI populate with info, give it a weight, then if you go to change Bat to the Special Skeleton, and select it, and THEN click save and quit it will crash.

And sorry, I actually got the crash when I hit SAVE AND QUIT, not when I selected the name.

**Comment by Crudedragos** [comment]
Still cannot seem to reproduce. Did you alter the NBT or something? Does it happen if you reduce to PZ + Special Mobs?

Album images from placing to selecting special skeleton: http://imgur.com/a/05CQU

**Comment by Blue001** [comment]
Found out what it was.... Noticed something different in my image to yours...
When I select the Special Skeleton, I didn't see Forge Properties and sai - 1.
In fact no properties are there at all...

![image](https://f.cloud.github.com/assets/4544521/576403/06436e26-c802-11e2-893b-6d2dcd08229a.png)

However, If I select the bat first... I see this...flying skeleton! weeee!

![image](https://f.cloud.github.com/assets/4544521/576388/127cb8d8-c801-11e2-9749-cf65ae6e2970.png)

This led me to think the NBT for the special skeleton was not being read for some reason. So I looked at the special mobs config.

I had set spawn_special_skeletons to false in the special mobs config. In fact I set everything in that config to false and 0, because I wanted to control spawning the special skeletons manually with JAS and not let it randomize the normal skeletons on its own.

_special_ai {
    I:_none=0
    I:ambush=0
    I:charge=0
    I:jump=0
    I:leap=0
    I:ninja=0
    I:shaman=0
    I:sprint=0
    I:throw=0

"skeleton rates" {
    B:_special_skeletons=false
    I:_vanilla=0
    I:fire=0
    I:gatling=0
    I:poison=0
    I:quick=0
    I:thief=0

So from what I can gather, when the custom spawner is trying to get the tags for the special skeletons, it seems to be unable to grab the NBT data for it, as it is disabled, so the last selected mob info stays (and why its blank when I select it first) and crashes? this is just conjecture...however.

Turning all the special mobs settings in its config back on and to 1's stopped the crash from happening, and the NBT tags were read by the spawner correctly after that. So something about the settings being off caused the issue. Not sure 'which' setting exactly. But I can test it some more if you want. In the end, it's not really an issue that is "caused" by PZ or Special Mobs, just how they interact with settings set a certain way. Unless you can somehow make it show a message somewhere saying "can't read NBT data" so the player knows it will crash if they try and save.
