### ISSUE TITLE
Mobs in leads taking 90% of server.tick()

### ISSUE THREAD

**Issue by cri5ti** [ProjectZulu/Project-Zulu#79]
I had an elephant tied to a fence with a lead and that caused my TPS to go from 20 to 2. 

![zulu](https://f.cloud.github.com/assets/731067/1420732/5cf73824-3fe4-11e3-81f3-e77431a20577.png)
- `minecraftforge-universal-1.6.2-9.10.1.871`
- `ProjectZuluCompletev1.1.5.5.zip`

**Comment by cri5ti** [comment]
This seems to happen only if the mob wants to go to some place, but the lead is holding him in place.

**Comment by Crudedragos** [comment]
Sounds like its failing to find a path so spams the pathfinding algorithm. The same thing happens to underground zombies in caves below villagers. They can't find a path and crush the server.

I'll to reproduce, which hopefully won't be difficult, and to combat it I'll try to place a minimum time to reattempt movement when pathfinding fails.
