### ISSUE TITLE
Server crash at mod atacks

### ISSUE THREAD

**Issue by serhiicherepanov** [ProjectZulu/Project-Zulu#97]
Hi, 

I tested mod on my server, time to time i have server crash.

Crash log: http://pastebin.com/syyPnV9q

**Comment by soultek101** [comment]
Hi there Sergey,

The crash is the result of you using an older version of Project Zulu (meant for MC 1.7.2)  as indicated here in the crash log...

ProjectZulu|Core{1.2.8.3} [Project Zulu](ProjectZulu-1.2.8.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available

You need to use the Project Zulu for Minecraft 1.7.10 located @ http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2185602-better-overworld-project-zulu-1-7-10-mobs-blocks#c7
and get PZ 1.3f version.

**Comment by serhiicherepanov** [comment]
@soultek101 oh, sorry. It's so hard to find actual release. Will be good if you can add binaries to github releases page

**Comment by soultek101** [comment]
No problem, I'm happy to help. I'll add the binaries very soon as per your suggestion. Thank you,
